version: "3"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    environment:
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    image: tanukievil1/mydockerproject
    depends_on:
      - db