FROM node:20.12.2
WORKDIR /app

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

COPY app/. .

RUN npm install -g jest

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make start
