services:
  app:
    image: tanukievil1/mydockerproject
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    depends_on:
      - db
    environment:
      - DATABASE_HOST=${{ secrets.DATABASE_HOST }}
      - DATABASE_NAME=${{ secrets.DATABASE_NAME }}
      - DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
      - DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}

  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:latest
    environment:
      - POSTGRES_USER=${{ secrets.DATABASE_USERNAME }}
      - POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
      - POSTGRES_DB=${{ secrets.DATABASE_NAME }}